modLoader = "kotlinforforge"

loaderVersion = "[4,)" # the loader is kotlin for forge
license = "{license}"
issueTrackerURL = "https://github.com/{githubUser}/{githubRepo}/issues"

[[mods]]
modId = "modid"
version = "1.0.0"
displayName = "ModName"
authors = "{author}"
description = '''
ModDescription
'''
updateJSONURL="https://raw.githubusercontent.com/{githubUser}/{githubRepo}/main/updates.json"
logoFile="icon.png"
[[dependencies.modid]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.modid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"
