name: build forge
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: ktlint check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          build-root-directory: forge
          arguments: ktlintCheck
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          build-root-directory: forge
          arguments: build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: forge/build/libs/
