name: build quilt
on:
  pull_request:
    branches: [ "**" ]
    paths:
      - .github/workflows/build-quilt.yml
      - build.gradle.kts
      - 'gradle.properties'
      - 'gradle/**'
      - 'buildSrc/**'
      - 'core/**'
      - 'quilt/**'
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/build-quilt.yml
      - build.gradle.kts
      - 'gradle.properties'
      - 'gradle/**'
      - 'buildSrc/**'
      - 'core/**'
      - 'quilt/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: ktlint check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          build-root-directory: quilt
          arguments: ktlintCheck
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          build-root-directory: quilt
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: quilt/build/libs/
