name: release fabric
on:
  push:
    tags:
      # Example: 1.0.0-MC1.19.x-fabric
      - "[0-9]+.[0-9]+.[0-9]+-MC[0-9]+.[0-9]+.[0-9]+-fabric"

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          build-root-directory: fabric
          arguments: build
      - name: Release
        uses: anton-yurchenko/git-release@main # https://github.com/marketplace/actions/git-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: fabric/build/libs/*
